INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('BTS','Proof','Born Singer',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('BTS','Proof','Boy In Luv',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('BTS','Proof','Blood Sweat & Tears',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('BTS','Proof','Burning Up (FIRE)',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('BTS','Proof','IDOL',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('BTS','Proof','Moon',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('BTS','MAP OF THE SOUL : 7','Black Swan',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('BTS','MAP OF THE SOUL : 7','Friends',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('BTS','BE','Dynamite',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('BTS','BE','Life Goes On',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('BTS','BE','Dis-ease',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Gen Hoshino','POP VIRUS','Pop Virus',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Gen Hoshino','POP VIRUS','Koi',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Gen Hoshino','POP VIRUS','Get a Feel',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Taylor Swift','Midnights','Lavender Haze',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Taylor Swift','Midnights','Maroon',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Taylor Swift','Midnights','Anti-Hero',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Taylor Swift','Midnights','Snow On The Beach (feat. Lana Del Rey)',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Taylor Swift','Midnights','You''re On Your Own, Kid',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Taylor Swift','Midnights','Midnight Rain',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Taylor Swift','Midnights','Question...?',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Taylor Swift','Midnights','Vigilante Shit',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Taylor Swift','Midnights','Bejeweled',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Taylor Swift','Midnights','Labyrinth',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Taylor Swift','Midnights','Karma',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Taylor Swift','Midnights','Sweet Nothing',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Taylor Swift','Midnights','Mastermind',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','Hybrid Theory (Bonus Edition)','In the End',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','Meteora','Numb',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','Minutes to Midnight','What I''ve Done',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','Hybrid Theory (Bonus Edition)','One Step Closer',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('JAY-Z','Numb / Encore: MTV Ultimate Mash-Ups Presents Collision Course','Numb / Encore',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','LIVING THINGS','LOST IN THE ECHO',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','LIVING THINGS','IN MY REMAINS',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','LIVING THINGS','BURN IT DOWN',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','LIVING THINGS','LIES GREED MISERY',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','LIVING THINGS','I''LL BE GONE',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','LIVING THINGS','CASTLE OF GLASS',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','LIVING THINGS','VICTIMIZED',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','LIVING THINGS','ROADS UNTRAVELED',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','LIVING THINGS','SKIN TO BONE',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','LIVING THINGS','UNTIL IT BREAKS',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','LIVING THINGS','TINFOIL',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','LIVING THINGS','POWERLESS',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','Minutes to Midnight','Wake',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','Minutes to Midnight','Given Up',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','Minutes to Midnight','Leave Out All The Rest',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','Minutes to Midnight','Bleed It Out',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','Minutes to Midnight','Shadow of the Day',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','Minutes to Midnight','Hands Held High',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','Minutes to Midnight','No More Sorrow',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','Minutes to Midnight','Valentine''s Day',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','Minutes to Midnight','In Between',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','Minutes to Midnight','In Pieces',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('Linkin Park','Minutes to Midnight','The Little Things Give You Away',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('YOASOBI','THE BOOK','Epilogue',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('YOASOBI','THE BOOK','Prologue',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('YOASOBI','THE BOOK 2','Romance',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','A・RA・SHI',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Sunrise Nippon',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','HORIZON',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Typhoon Generation',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Kansya Kangeki Ame Arashi',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Kimi No Tame Ni Boku Ga Iru',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Jidai',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','a Day in Our Life',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','La tormenta 2004',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Nice Na Kokoroiki',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','PIKA☆NCHI',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Tomadoinagara',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Hadashi No Mirai',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Kotoba Yori Taisetsuna Mono',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','PIKA☆☆NCHI DOUBLE',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Hitomi No Naka No Galaxy',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Hero',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Sakura Sake',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','WISH',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Kitto Daijyoubu',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Aozora Pedal',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Love so sweet',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','We can make it !',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Happiness',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Step and Go',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','One Love',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','truth',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Kaze No Mukou E',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Beautiful days',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Believe',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Ahita No Kioku',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Crazy Moon-Kimi Wa Muteki-',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','5×10',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Attack it!',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Everything',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','My Girl',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Troublemaker',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Monster',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','To be free',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Love Rainbow',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Dear Snow',1);
INSERT INTO artist(l_artist_name,l_album_name,l_song_title,uid) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Hatenai Sora',1);
