INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('BTS','Proof','Born Singer',74);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('BTS','Proof','Boy In Luv',62);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('BTS','Proof','Blood Sweat & Tears',63);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('BTS','Proof','Burning Up (FIRE)',62);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('BTS','Proof','IDOL',62);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('BTS','Proof','Moon',63);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('BTS','MAP OF THE SOUL : 7','Black Swan',74);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('BTS','MAP OF THE SOUL : 7','Friends',70);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('BTS','BE','Dynamite',85);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('BTS','BE','Life Goes On',78);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('BTS','BE','Dis-ease',68);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Gen Hoshino','POP VIRUS','Pop Virus',47);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Gen Hoshino','POP VIRUS','Koi',53);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Gen Hoshino','POP VIRUS','Get a Feel',31);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Taylor Swift','Midnights','Lavender Haze',89);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Taylor Swift','Midnights','Maroon',88);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Taylor Swift','Midnights','Anti-Hero',91);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Taylor Swift','Midnights','Snow On The Beach (feat. Lana Del Rey)',88);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Taylor Swift','Midnights','You''re On Your Own, Kid',87);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Taylor Swift','Midnights','Midnight Rain',87);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Taylor Swift','Midnights','Question...?',86);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Taylor Swift','Midnights','Vigilante Shit',86);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Taylor Swift','Midnights','Bejeweled',85);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Taylor Swift','Midnights','Labyrinth',85);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Taylor Swift','Midnights','Karma',86);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Taylor Swift','Midnights','Sweet Nothing',84);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Taylor Swift','Midnights','Mastermind',84);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','Hybrid Theory (Bonus Edition)','In the End',85);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','Meteora','Numb',83);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','Minutes to Midnight','What I''ve Done',79);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','Hybrid Theory (Bonus Edition)','One Step Closer',77);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('JAY-Z','Numb / Encore: MTV Ultimate Mash-Ups Presents Collision Course','Numb / Encore',78);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','LIVING THINGS','LOST IN THE ECHO',66);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','LIVING THINGS','IN MY REMAINS',62);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','LIVING THINGS','BURN IT DOWN',74);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','LIVING THINGS','LIES GREED MISERY',51);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','LIVING THINGS','I''LL BE GONE',54);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','LIVING THINGS','CASTLE OF GLASS',73);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','LIVING THINGS','VICTIMIZED',50);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','LIVING THINGS','ROADS UNTRAVELED',64);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','LIVING THINGS','SKIN TO BONE',51);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','LIVING THINGS','UNTIL IT BREAKS',48);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','LIVING THINGS','TINFOIL',45);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','LIVING THINGS','POWERLESS',60);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','Minutes to Midnight','Wake',45);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','Minutes to Midnight','Given Up',71);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','Minutes to Midnight','Leave Out All The Rest',69);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','Minutes to Midnight','Bleed It Out',76);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','Minutes to Midnight','Shadow of the Day',66);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','Minutes to Midnight','Hands Held High',52);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','Minutes to Midnight','No More Sorrow',62);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','Minutes to Midnight','Valentine''s Day',51);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','Minutes to Midnight','In Between',49);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','Minutes to Midnight','In Pieces',54);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('Linkin Park','Minutes to Midnight','The Little Things Give You Away',50);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('YOASOBI','THE BOOK','Epilogue',49);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('YOASOBI','THE BOOK','Prologue',49);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('YOASOBI','THE BOOK 2','Romance',57);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','A・RA・SHI',16);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Sunrise Nippon',13);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','HORIZON',11);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Typhoon Generation',12);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Kansya Kangeki Ame Arashi',14);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Kimi No Tame Ni Boku Ga Iru',13);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Jidai',12);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','a Day in Our Life',12);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','La tormenta 2004',18);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Nice Na Kokoroiki',11);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','PIKA☆NCHI',11);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Tomadoinagara',13);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Hadashi No Mirai',11);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Kotoba Yori Taisetsuna Mono',12);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','PIKA☆☆NCHI DOUBLE',14);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Hitomi No Naka No Galaxy',11);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Hero',13);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Sakura Sake',14);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','WISH',13);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Kitto Daijyoubu',11);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Aozora Pedal',12);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Love so sweet',15);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','We can make it !',11);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Happiness',13);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Step and Go',12);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','One Love',33);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','truth',20);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Kaze No Mukou E',13);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Beautiful days',17);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Believe',18);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Ahita No Kioku',14);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Crazy Moon-Kimi Wa Muteki-',12);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','5×10',23);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Attack it!',20);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Everything',11);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','My Girl',11);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Troublemaker',11);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Monster',12);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','To be free',9);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Love Rainbow',10);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Dear Snow',10);
INSERT INTO song(s_artist_name,s_album_name,song_title,average_rating) VALUES ('ARASHI','5×20 All the BEST!! 1999-2019 (Special Edition)','Hatenai Sora',11);
